### ISSUE TITLE
Incorrect inference commands in Readme.md

### ISSUE THREAD

**Issue by mhalber** [art-programmer/MASC#6]
Hi, it seems there is a typo with inference commands in the Readme.md, specifically, the split command is missing double hyphen:
~~~
python inference.py --dataFolder=[SCANNET_PATH] --task=predict_cluster_write split=test
~~~
I believe correct command should be:
~~~
python inference.py --dataFolder=[SCANNET_PATH] --task=predict_cluster_write --split=test
~~~

**Comment by mhalber** [comment]
I believe there is another issue with the Readme.md. Can we confirm that command to train confidence model should be:
~~~
python train_confidence.py --restore=0 --dataFolder=[SCANNET_PATH]
~~~
rather than stated
~~~
python train.py --restore=0 --dataFolder=[SCANNET_PATH]
~~~

**Comment by art-programmer** [comment]
Thanks for the corrections!
